{% set name = "spectate" %}
{% set version = "1.0.0" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: a7eb2d4d5c2d64cd8b9614f8590a5d1816be88f6e3572963e9f02f7c43502709

build:
  number: 2
  skip: true  # [py<36]
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python
    - pip
  run:
    - python

test:
  imports:
    - spectate
  requires:
    - pytest
  commands:
    - cd test && python -m test_core.py


about:
  home: https://github.com/rmorshea/spectate/
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: A library for Python 2 and 3 that can track changes to mutable data types.

  description: |
    With spectate complicated protocols for managing updates, don't need to be 
    the outward responsibility of a user, and can instead be done automagically 
    in the background. For instance, syncing the state between a server and 
    client can controlled by spectate so user's don't have to.
  doc_url: https://python-spectate.readthedocs.io/en/latest/
  dev_url: https://github.com/rmorshea/spectate/

extra:
  recipe-maintainers:
    - marimeireles
    - wolfv
    - SylvainCorlay
